/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/giftbox.glb 
*/

import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/giftbox.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Giftbox01.geometry} material={materials.Pink01} position={[0.001, 1.058, 0]} />
      <mesh geometry={nodes.Giftbox02.geometry} material={materials.Pink02} position={[0.001, 1.307, 0]} rotation={[0, Math.PI / 2, 0]} scale={1.026} />
      <mesh geometry={nodes.Giftbox03.geometry} material={materials.Pink02} position={[0.009, 2.189, 0]} rotation={[0, -Math.PI / 4, 0]} />
      <mesh geometry={nodes.Giftbox04.geometry} material={materials.Pink03} position={[0.009, 2.189, 0]} rotation={[-0.051, 0, 0]} scale={[0.183, 0.403, 0.363]} />
      <mesh geometry={nodes.Giftbox05.geometry} material={materials.Pink01} position={[0.009, 2.189, 0]} />
      <mesh geometry={nodes.Giftbox06.geometry} material={materials.Yellow01} position={[0.003, 2.377, 0.007]} scale={0.168} />
    </group>
  )
}

useGLTF.preload('/giftbox.glb')
